### PR TITLE
MX Translation

### PR DESCRIPTION
**Pull request by ghost**
:)

### CODE REVIEW

**Comment by Deevad** [comment]
many thanks  !

**Comment by Deevad** [comment]
it's online ! http://www.peppercarrot.com/mx/article298/episode-10-summer-special , I think I found typos in the credits ; I'll give you the permission to directly edit the files on 'master' if you want to correct. Thank you!

**Comment by ghost** [comment]
Deevad Sensei, I just went ahead with another pull-request, but if I would to correct on the "master", is that the same process, or is there an additional steps to it? I don't mind, specially if helps you with the tasks of merging.

**Comment by Deevad** [comment]
@RJQuiralta  :) I'll merge it very soon, and render later this evening ( after swimming pool time xD ) . I just created the 'pepper&carrot translator' mailing-list , I sent you an invitation. I hope it will be a good tool. Thank you for the corrections!

**Comment by ghost** [comment]
Neat! I got the invitation, happy to collaborate as I keep learning all this processes, as I getting older things don't come easy on my head :D Thank you!

**Pull request merged**
